language: node_js
node_js:
  - "node"
  - "lts/*"
  - "14"
os:
  - linux
  - osx
  - windows
install:
  - make installGlobal
  - make install
cache:
  directories:
    - "node_modules"
script:
  - npm run lint
  - npm test